spring:
  data:
    mongodb:
       uri: mongodb://mongo:27017/registrationdb

tickets:
  events:
    url: http://events:8081

management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
