# values.yaml

# Default values for eventservice_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred  # Ensure this is included

# Other configurations...

mongo:
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent

postgres:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent

eventservice:
  image:
    repository: "your-docker-repo/events"  # Add the repository
    tag: "latest"  # Set the appropriate tag
    pullPolicy: "IfNotPresent"  # Set the pull policy

registrationservice:
  image:
    repository: "your-docker-repo/registration"  # Add the repository
    tag: "latest"  # Set the appropriate tag
    pullPolicy: "IfNotPresent"  # Set the pull policy