IMAGE_TAG_EVENT_SERVICE: "${IMAGE_TAG_EVENT_SERVICE}"
IMAGE_TAG_REGISTRATION_SERVICE: "${IMAGE_TAG_REGISTRATION_SERVICE}"
# IMAGE_TAG_GRAFANA_SERVICE: "${IMAGE_TAG_GRAFANA_SERVICE}"
# IMAGE_TAG_PROMETHEUS_SERVICE: "${IMAGE_TAG_PROMETHEUS_SERVICE}"
DNS_NAME: "tecitlab.org"