replicaCount: 1

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 8083

readinessProbe:
  httpGet:
    path: /
    port: 8083

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

registrationService:
  image:
    repository: 533266982090.dkr.ecr.us-east-1.amazonaws.com/eventservice-repo/registration-service
    tag: latest

eventService:
  image:
    repository: 533266982090.dkr.ecr.us-east-1.amazonaws.com/eventservice-repo/event-service
    tag: latest



# prometheus:
#   server:
#     image:
#       repository: prom/prometheus
#       tag: v2.52.0

# grafana:
#   server:
#     image:
#       repository: grafana/grafana
#       tag: 10.3.1
