apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventservice_chart.fullname" . }}-event-service
  labels:
    app.kubernetes.io/name: {{ include "eventservice_chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: event-service
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: {{ include "eventservice_chart.name" . }}
    app.kubernetes.io/component: event-service
    app.kubernetes.io/instance: {{ .Release.Name }}
