apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o eventservice_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: events  # <- standardized to match Deployment
  name: events
spec:
  type: ClusterIP
  selector:
    app: events  # <- must match Deployment pod labels
  ports:
    - name: http
      port: 8081
      targetPort: 8081
