apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    io.kompose.service: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 27017
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
