apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventservice_chart.fullname" . }}-registration-service
  labels:
    app.kubernetes.io/name: {{ include "eventservice_chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: registration-service
spec:
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  selector:
    app.kubernetes.io/name: {{ include "eventservice_chart.name" . }}
    app.kubernetes.io/component: registration-service
    app.kubernetes.io/instance: {{ .Release.Name }}
