apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o eventservice_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: registration
  name: registration
spec:
  type: NodePort
  selector:
    io.kompose.service: registration
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
