# _chart/values-template.yaml

IMAGE_TAG_EVENTS: "${IMAGE_TAG_EVENTS}"
IMAGE_TAG_REGISTRATION: "${IMAGE_TAG_REGISTRATION}"
IMAGE_TAG_MONGO: "${IMAGE_TAG_MONGO}"
IMAGE_TAG_POSTGRES: "${IMAGE_TAG_POSTGRES}"
DNS_NAME: "tecitlab.org"
